# Generated by Django 5.1.5 on 2025-04-18 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aadhar',
            name='aadhar_number',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
