# Generated by Django 5.1.5 on 2025-04-21 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_aadhar_aadhar_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='aadhar',
            name='pan',
            field=models.CharField(default='ASDFG1234H', max_length=10),
        ),
    ]
