# Generated by Django 5.1.5 on 2025-04-21 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_aadhar_pan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aadhar',
            name='pan',
            field=models.CharField(max_length=10),
        ),
    ]
